Repository soon-my-room/soon_my_room, pull requests merged in 2022-07, with the labels that each got.

#25 feat: 프로필 설정 페이지 개발
  src/App.jsx
  src/pages/ProfileSettingPage.jsx
Labels: enhancement

#113 feat: UserProfileImg 컴포넌트에 src props 추가
  src/components/profileImg/UserProfileImg.jsx
Labels: feat

#103 feat: Postitem 데이터 연결
  src/components/post/PostItem.jsx
  src/components/post/PostList.jsx
Labels: feat

#114 feat: 상품등록시 이미지등록하는 input 컴포넌트 개발
  src/components/common/input/InputImageUploadBox.jsx
Labels: feat

#118 feat: 프로필카드에 팔로잉, 팔로우 버튼 UI컴포넌트 추가
  src/components/userProfile/ProfileContainer.jsx
  src/components/userProfile/ProfileDataCard.jsx
Labels: feat, fix

#127 feat: PostViewChangeNav컴포넌트에 게시글(리스트형/앨범형) 전환 기능 추가
  src/components/common/nav/PostViewChangeNav.jsx
  src/components/post/PostItem.jsx
  src/components/post/PostList.jsx
Labels: feat

#129 feat: 프로필페이지에서 상품 클릭시 모달 열고 닫히는 기능 개발
  src/components/common/modal/ModalContainer.jsx
  src/components/product/ProductListOnSales.jsx
  src/components/product/ProductOnSales.jsx
  src/pages/ProfilePage.jsx
Labels: feat, ui

#132 feat: TopNavBasic, TopNavUpload 컴포넌트 뒤로가기 버튼 클릭시 이전 페이지로 갈 수 있도록 수정
  src/components/common/nav/TopNavBasic.jsx
  src/components/common/nav/TopNavUpload.jsx
  src/pages/FollowPage.jsx
  src/pages/ProductAddPage.jsx
  src/pages/ProfileEditPage.jsx
Labels: fix

#130 feat: 포스트뷰/앨범뷰 버튼 클릭 시 이미지 예외처리 함수추가
  src/components/post/PostItem.jsx
  src/components/post/PostList.jsx
Labels: feat

#133 feat: 판매중인 상품에서 상품을 누르고 수정을 누르면 수정페이지로 이동하고 상품정보가 보이도록 기능 개발
  src/components/common/input/InputImageUploadBox.jsx
  src/components/product/ProductForm.jsx
  src/components/product/ProductListOnSales.jsx
  src/components/product/ProductOnSales.jsx
  src/pages/ProductEditPage.jsx
  src/pages/ProfilePage.jsx
Labels: feat

#134 feat: 프로필 수정, 상품 등록 페이지 이동 링크 추가
  src/components/userProfile/ProfileDataCard.jsx
Labels: feat

#142 feat: 프로필 카드의 팔로우/언팔로우 기능 개발
  src/components/userProfile/ProfileContainer.jsx
  src/components/userProfile/ProfileDataCard.jsx
Labels: feat

#145 feat: 게시글 좋아요 기능 구현
  src/assets/icon/icon-heart.svg
  src/components/post/PostItem.jsx
Labels: feat

#151 feat: 프로필 수정 페이지 개발
  src/components/profileImg/ProfileImg.jsx
  src/pages/ProfileEditPage.jsx
Labels: feat

#153 fix: splash화면이 오른쪽으로 치우쳐지는 오류 해결
  src/components/splash/Splash.jsx
  src/pages/LoginHomePage.jsx
Labels: fix

#154 feat: 프로필 수정 기능 개발
  src/App.jsx
  src/apis/imageApi.js
  src/apis/index.js
  src/apis/profileApi.js
  src/pages/ProfileEditPage.jsx
  src/utils/route/PrivateRoute.jsx
Labels: feat

#157 refactor: 이미지 저장하는 함수를 axiosImageSave 공통함수로 변경
  src/pages/ProductAddPage.jsx
  src/pages/ProfilePage.jsx
Labels: refactor

#156 design: 디자인 메인컬러 변경 및 일괄 수정
  src/assets/icon/icon-email.svg
  src/assets/icon/icon-signup.svg
  src/assets/icon/tab/icon-home-fill.svg
  src/assets/icon/tab/icon-message-circle-fill.svg
  src/assets/icon/tab/icon-user-fill.svg
  src/assets/upload-file.svg
  src/components/common/button/Button.jsx
  src/components/common/input/InputBox.jsx
  src/components/common/modal/DeleteModal.jsx
  src/components/product/ProductOnSales.jsx
  src/components/profileImg/ProfileImg.jsx
  src/components/userProfile/ProfileDataCard.jsx
  src/index.jsx
  src/pages/PostAddPage.jsx
Labels: ui

#163 fix: axios 이용시 토큰정보를 받아오지 못하는 이슈를 발견해서 인터셉터를 이용해서 처리
  src/apis/index.js
Labels: fix

#160 feat: 게시글 모달 연결 및 기능 개발
  src/apis/postApi.js
  src/components/common/modal/DeleteModal.jsx
  src/components/common/modal/ModalContainer.jsx
  src/components/post/PostItem.jsx
  src/components/post/PostList.jsx
Labels: feat

#165 feat: 프로필에서 팔로우, 팔로워 버튼을 누르면 해당 계정에 팔로우, 팔로워가 나올 수 있도록 기능 개발
  src/App.jsx
  src/apis/followApi.js
  src/components/followProfile/FollowProfileList.jsx
  src/components/userProfile/ProfileDataCard.jsx
Labels: feat

#171 feat: follow 페이지에서 상대방 유저이름, 유저이미지, 유저소개를 클릭하면 상대방페이지로 이동할 수 있도록 기능 추가
  src/App.jsx
  src/apis/followApi.js
  src/components/followProfile/FollowProfileCard.jsx
  src/components/followProfile/FollowProfileList.jsx
  src/components/userProfile/ProfileDataCard.jsx
  src/pages/FollowPage.jsx
Labels: feat, refactor, ui

#177 feat: 게시물에 댓글 볼수 있도록 기능 구현
  src/apis/postApi.js
  src/components/post/CommentItem.jsx
  src/components/post/PostItem.jsx
  src/pages/PostPage.jsx
Labels: feat

#172 feat: 판매중인상품 삭제시 삭제안내모달이 나오도록 기능 추가
  src/components/common/modal/DeleteModal.jsx
  src/pages/ProfilePage.jsx
Labels: feat

#173 refactor: 상품추가, 상품수정 페이지를 하나로 통합
  src/App.jsx
  src/apis/productApi.js
  src/components/product/ProductForm.jsx
  src/pages/ProductAddPage.jsx
  src/pages/ProductEditPage.jsx
  src/pages/ProductPage.jsx
Labels: refactor

#179 feat: 댓글 작성시 작성한 댓글이 맨위에 보일 수 있도록 기능 추가 및 코드 리팩토링
  src/apis/postApi.js
  src/components/post/CommentAddBox.jsx
  src/pages/PostPage.jsx
Labels: refactor, fix

#181 feat: 댓글 삭제 기능 개발
  src/apis/postApi.js
  src/components/post/CommentItem.jsx
  src/pages/PostPage.jsx
Labels: feat

#182 feat: 프로필 수정시 프로필 화면으로 바로 이동하도록 기능 수정
  src/pages/ProfileEditPage.jsx
Labels: feat

#189 feat: 댓글 더보기 모달에서 모달 바깥을 클릭하면 모달이 닫히도록 기능 추가
  src/components/post/CommentItem.jsx
Labels: feat

#191 feat: 판매중인 상품을 누르고 삭제시 팝업모달이 나오며 삭제버튼을 누르면 삭제가 가능하도록 기능 수정
  src/components/common/modal/DeleteModal.jsx
  src/pages/ProfilePage.jsx
Labels: feat

#192 refactor: 모달이 여러곳에서 사용되서 확장성을 위해 모달 컴포넌트의 이름 변경 및 속성명을 수정
  src/components/common/modal/AlertModal.jsx
  src/components/common/nav/TopNavBasic.jsx
  src/components/post/PostItem.jsx
  src/pages/ProfilePage.jsx
Labels: refactor

#193 feat: 게시글 수정 페이지 개발
  src/App.jsx
  src/apis/postApi.js
  src/components/post/PostItem.jsx
  src/pages/PostEditPage.jsx
Labels: feat

#194 fix: 게시글 수정시 프로필 이미지가 안나오는 에러 수정
  src/pages/PostEditPage.jsx
Labels: fix

#195 feat: 게시글 수정시 게시글이 있으면 이미지를 삭제 또는 추가만 해도 게시글이 수정되도록 기능 추가
  src/pages/PostEditPage.jsx
Labels: feat, refactor

#196 feat: 게시글 이미지 업로드할때 여러장 한번에 가능하도록 기능 추가
  src/pages/PostEditPage.jsx
Labels: feat, refactor

#197 fix: 게시글 이미지 업로드시 이미지가 3장이 넘으면 업로드가 안되도록 수정
  src/pages/PostEditPage.jsx
Labels: fix

#200 refactor: 포스트추가페이지와 포스트수정페이지를 하나로 통합
  src/App.jsx
  src/pages/PostEditPage.jsx
  src/pages/PostUploadPage.jsx
Labels: refactor

#202 refactor: 게시글 업로드버튼을 게시글 폼 안으로 이동
  src/pages/PostUploadPage.jsx
Labels: refactor

#203 refactor: 판매중인 상품 금액에 콤마가 나올 수 있도록 개선
  src/components/product/ProductOnSales.jsx
Labels: refactor

#204 fix: 게시물에서 하트를 누르고 상세페이지로 넘어가면 하트가 반영이 안되어있는 에러 수정
  src/components/post/PostItem.jsx
Labels: fix

#205 refactor: 게시물상세페이지에서 새롭게 게시물데이터를 조회하고 보여줄 수 있도록 수정
  src/components/post/PostItem.jsx
  src/pages/PostPage.jsx
Labels: refactor

#201 refactor: 로그아웃 모달 함수명 수정
  src/components/common/nav/TopNavBasic.jsx
Labels: refactor

#207 feat: 댓글 작성 시간 추가
  src/components/post/CommentItem.jsx
Labels: feat

#208 feat: 유저조회시 일치하는단어 색나오게 하는것과 기본프로필이미지가 지정한것으로 나오도록 기능 추가
  src/components/search/SearchCard.jsx
  src/components/search/SearchCardList.jsx
  src/pages/SearchPage.jsx
  src/utils/defaultImage.js
Labels: feat

#210 feat: 댓글 시간작성 표기시 '몇시간전' 추가
  src/components/post/CommentItem.jsx
Labels: feat

#214 design: 댓글창에서 프로필이미지와 유저이름에 마우스를 올리면 커서로 보이도록 UI 개선
  src/components/post/CommentItem.jsx
Labels: ui

#215 fix: 검색시 유저이름과 계정ID에 일치하는 단어가 하이라이트 되도록 수정
  src/components/search/SearchCard.jsx
Labels: fix
